package com.example.compose
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006A65)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9DF1EB)
val onPrimaryContainerLight = Color(0xFF00504C)
val secondaryLight = Color(0xFF8D4D2D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDBCC)
val onSecondaryContainerLight = Color(0xFF703718)
val tertiaryLight = Color(0xFF006A65)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9DF2EA)
val onTertiaryContainerLight = Color(0xFF00504C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF4FBF9)
val onBackgroundLight = Color(0xFF161D1C)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF221A16)
val surfaceVariantLight = Color(0xFFF4DED5)
val onSurfaceVariantLight = Color(0xFF52443D)
val outlineLight = Color(0xFF85736C)
val outlineVariantLight = Color(0xFFD8C2BA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E2A)
val inverseOnSurfaceLight = Color(0xFFFFEDE6)
val inversePrimaryLight = Color(0xFF81D5CE)
val surfaceDimLight = Color(0xFFE8D7D0)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EB)
val surfaceContainerLight = Color(0xFFFCEAE3)
val surfaceContainerHighLight = Color(0xFFF6E5DE)
val surfaceContainerHighestLight = Color(0xFFF0DFD8)


val primaryDark = Color(0xFF81D5CE)
val onPrimaryDark = Color(0xFF003734)
val primaryContainerDark = Color(0xFF00504C)
val onPrimaryContainerDark = Color(0xFF9DF1EB)
val secondaryDark = Color(0xFFFFB693)
val onSecondaryDark = Color(0xFF542104)
val secondaryContainerDark = Color(0xFF703718)
val onSecondaryContainerDark = Color(0xFFFFDBCC)
val tertiaryDark = Color(0xFF81D5CE)
val onTertiaryDark = Color(0xFF003734)
val tertiaryContainerDark = Color(0xFF00504C)
val onTertiaryContainerDark = Color(0xFF9DF2EA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1514)
val onBackgroundDark = Color(0xFFDDE4E2)
val surfaceDark = Color(0xFF1A120E)
val onSurfaceDark = Color(0xFFF0DFD8)
val surfaceVariantDark = Color(0xFF52443D)
val onSurfaceVariantDark = Color(0xFFD8C2BA)
val outlineDark = Color(0xFFA08D85)
val outlineVariantDark = Color(0xFF52443D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DFD8)
val inverseOnSurfaceDark = Color(0xFF382E2A)
val inversePrimaryDark = Color(0xFF006A65)
val surfaceDimDark = Color(0xFF1A120E)
val surfaceBrightDark = Color(0xFF423732)
val surfaceContainerLowestDark = Color(0xFF140C09)
val surfaceContainerLowDark = Color(0xFF221A16)
val surfaceContainerDark = Color(0xFF271E1A)
val surfaceContainerHighDark = Color(0xFF322824)
val surfaceContainerHighestDark = Color(0xFF3D332E)









